In [114]:
import pandas as pd
import numpy as np
import quandl
from talib.abstract import *
import datetime
def dateparse (time_in_secs):    
    return datetime.datetime.fromtimestamp(float(time_in_secs))

In [152]:
df = pd.read_csv("15min_data.csv")

In [103]:
data = quandl.get("BITFINEX/BTCUSD")

In [153]:
df

,Unnamed: 0,timestamp,high,low,close,open,volume_btc,volume_currency
0,0,2014-12-01 00:33:00,300.00,300.00,300.00,300.00,0.150000,4.500000e+01
1,1,2014-12-01 00:48:00,300.00,300.00,300.00,300.00,0.150000,4.500000e+01
2,2,2014-12-01 01:03:00,300.00,300.00,300.00,300.00,0.150000,4.500000e+01
3,3,2014-12-01 01:18:00,370.00,300.00,370.00,300.00,0.150000,5.130000e+01
4,4,2014-12-01 01:33:00,370.00,370.00,370.00,370.00,0.150000,5.550000e+01
5,5,2014-12-01 01:48:00,370.00,370.00,370.00,370.00,0.365222,1.351321e+02
6,6,2014-12-01 02:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
7,7,2014-12-01 02:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
8,8,2014-12-01 02:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
9,9,2014-12-01 02:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
10,10,2014-12-01 03:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
11,11,2014-12-01 03:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
12,12,2014-12-01 03:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
13,13,2014-12-01 03:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
14,14,2014-12-01 04:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
15,15,2014-12-01 04:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
16,16,2014-12-01 04:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
17,17,2014-12-01 04:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
18,18,2014-12-01 05:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
19,19,2014-12-01 05:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
20,20,2014-12-01 05:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
21,21,2014-12-01 05:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
22,22,2014-12-01 06:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
23,23,2014-12-01 06:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
24,24,2014-12-01 06:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
25,25,2014-12-01 06:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
26,26,2014-12-01 07:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
27,27,2014-12-01 07:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
28,28,2014-12-01 07:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
29,29,2014-12-01 07:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
...,...,...,...,...,...,...,...,...
97221,97221,2017-10-19 12:30:00,5685.96,5655.00,5685.96,5665.14,78.391742,4.444983e+05
97222,97222,2017-10-19 12:45:00,5685.96,5675.76,5678.42,5685.96,71.956912,4.089252e+05
97223,97223,2017-10-19 13:00:00,5683.52,5670.00,5678.06,5678.42,58.605910,3.326861e+05
97224,97224,2017-10-19 13:15:00,5678.06,5655.13,5655.13,5678.06,68.617766,3.889120e+05
97225,97225,2017-10-19 13:30:00,5663.06,5655.12,5663.06,5655.13,68.220114,3.859560e+05
97226,97226,2017-10-19 13:45:00,5674.60,5663.05,5674.60,5663.06,76.979622,4.362084e+05
97227,97227,2017-10-19 14:00:00,5676.06,5663.10,5665.01,5674.72,74.600527,4.229147e+05
97228,97228,2017-10-19 14:15:00,5665.03,5655.12,5655.13,5665.01,62.190277,3.521329e+05
97229,97229,2017-10-19 14:30:00,5668.00,5655.13,5668.00,5655.13,54.887206,3.107793e+05
97230,97230,2017-10-19 14:45:00,5673.11,5668.00,5673.11,5668.00,55.762919,3.162648e+05
97231,97231,2017-10-19 15:00:00,5673.11,5667.00,5667.01,5673.11,94.359056,5.350551e+05
97232,97232,2017-10-19 15:15:00,5667.01,5657.17,5659.30,5667.01,154.283312,8.737901e+05
97233,97233,2017-10-19 15:30:00,5659.30,5626.00,5630.00,5659.30,164.343122,9.272045e+05
97234,97234,2017-10-19 15:45:00,5634.96,5629.99,5634.96,5630.00,55.401830,3.120199e+05
97235,97235,2017-10-19 16:00:00,5641.96,5634.95,5636.79,5634.96,127.491412,7.187532e+05
97236,97236,2017-10-19 16:15:00,5694.99,5636.78,5692.83,5636.79,194.448498,1.102493e+06
97237,97237,2017-10-19 16:30:00,5694.00,5690.05,5694.00,5692.83,93.076236,5.298612e+05
97238,97238,2017-10-19 16:45:00,5719.49,5694.00,5701.69,5694.00,142.513570,8.130939e+05
97239,97239,2017-10-19 17:00:00,5710.00,5696.00,5698.52,5701.69,105.029410,5.992791e+05
97240,97240,2017-10-19 17:15:00,5708.11,5695.00,5701.91,5698.53,70.236143,4.005051e+05
97241,97241,2017-10-19 17:30:00,5702.00,5691.09,5700.44,5701.91,88.787331,5.059870e+05
97242,97242,2017-10-19 17:45:00,5719.71,5700.43,5719.70,5700.44,135.376703,7.734320e+05
97243,97243,2017-10-19 18:00:00,5729.98,5719.69,5719.99,5719.70,121.220791,6.938694e+05
97244,97244,2017-10-19 18:15:00,5719.99,5690.91,5709.95,5719.99,83.856620,4.784865e+05
97245,97245,2017-10-19 18:30:00,5730.00,5705.00,5727.79,5705.00,100.337837,5.739507e+05
97246,97246,2017-10-19 18:45:00,5730.00,5690.00,5711.71,5727.79,116.482618,6.665413e+05
97247,97247,2017-10-19 19:00:00,5723.49,5689.97,5719.74,5711.71,101.137744,5.775619e+05
97248,97248,2017-10-19 19:15:00,5724.99,5710.00,5710.01,5719.74,87.488958,5.003607e+05
97249,97249,2017-10-19 19:30:00,5714.97,5705.25,5712.92,5710.01,36.541138,2.086246e+05
97250,97250,2017-10-19 19:45:00,5712.92,5700.00,5704.01,5712.92,52.212121,2.978099e+05

In [154]:
df.rename(columns={'volume_currency': 'volume'}, inplace=True)
df

,Unnamed: 0,timestamp,high,low,close,open,volume_btc,volume
0,0,2014-12-01 00:33:00,300.00,300.00,300.00,300.00,0.150000,4.500000e+01
1,1,2014-12-01 00:48:00,300.00,300.00,300.00,300.00,0.150000,4.500000e+01
2,2,2014-12-01 01:03:00,300.00,300.00,300.00,300.00,0.150000,4.500000e+01
3,3,2014-12-01 01:18:00,370.00,300.00,370.00,300.00,0.150000,5.130000e+01
4,4,2014-12-01 01:33:00,370.00,370.00,370.00,370.00,0.150000,5.550000e+01
5,5,2014-12-01 01:48:00,370.00,370.00,370.00,370.00,0.365222,1.351321e+02
6,6,2014-12-01 02:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
7,7,2014-12-01 02:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
8,8,2014-12-01 02:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
9,9,2014-12-01 02:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
10,10,2014-12-01 03:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
11,11,2014-12-01 03:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
12,12,2014-12-01 03:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
13,13,2014-12-01 03:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
14,14,2014-12-01 04:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
15,15,2014-12-01 04:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
16,16,2014-12-01 04:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
17,17,2014-12-01 04:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
18,18,2014-12-01 05:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
19,19,2014-12-01 05:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
20,20,2014-12-01 05:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
21,21,2014-12-01 05:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
22,22,2014-12-01 06:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
23,23,2014-12-01 06:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
24,24,2014-12-01 06:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
25,25,2014-12-01 06:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
26,26,2014-12-01 07:03:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
27,27,2014-12-01 07:18:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
28,28,2014-12-01 07:33:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
29,29,2014-12-01 07:48:00,370.00,370.00,370.00,370.00,0.398333,1.473832e+02
...,...,...,...,...,...,...,...,...
97221,97221,2017-10-19 12:30:00,5685.96,5655.00,5685.96,5665.14,78.391742,4.444983e+05
97222,97222,2017-10-19 12:45:00,5685.96,5675.76,5678.42,5685.96,71.956912,4.089252e+05
97223,97223,2017-10-19 13:00:00,5683.52,5670.00,5678.06,5678.42,58.605910,3.326861e+05
97224,97224,2017-10-19 13:15:00,5678.06,5655.13,5655.13,5678.06,68.617766,3.889120e+05
97225,97225,2017-10-19 13:30:00,5663.06,5655.12,5663.06,5655.13,68.220114,3.859560e+05
97226,97226,2017-10-19 13:45:00,5674.60,5663.05,5674.60,5663.06,76.979622,4.362084e+05
97227,97227,2017-10-19 14:00:00,5676.06,5663.10,5665.01,5674.72,74.600527,4.229147e+05
97228,97228,2017-10-19 14:15:00,5665.03,5655.12,5655.13,5665.01,62.190277,3.521329e+05
97229,97229,2017-10-19 14:30:00,5668.00,5655.13,5668.00,5655.13,54.887206,3.107793e+05
97230,97230,2017-10-19 14:45:00,5673.11,5668.00,5673.11,5668.00,55.762919,3.162648e+05
97231,97231,2017-10-19 15:00:00,5673.11,5667.00,5667.01,5673.11,94.359056,5.350551e+05
97232,97232,2017-10-19 15:15:00,5667.01,5657.17,5659.30,5667.01,154.283312,8.737901e+05
97233,97233,2017-10-19 15:30:00,5659.30,5626.00,5630.00,5659.30,164.343122,9.272045e+05
97234,97234,2017-10-19 15:45:00,5634.96,5629.99,5634.96,5630.00,55.401830,3.120199e+05
97235,97235,2017-10-19 16:00:00,5641.96,5634.95,5636.79,5634.96,127.491412,7.187532e+05
97236,97236,2017-10-19 16:15:00,5694.99,5636.78,5692.83,5636.79,194.448498,1.102493e+06
97237,97237,2017-10-19 16:30:00,5694.00,5690.05,5694.00,5692.83,93.076236,5.298612e+05
97238,97238,2017-10-19 16:45:00,5719.49,5694.00,5701.69,5694.00,142.513570,8.130939e+05
97239,97239,2017-10-19 17:00:00,5710.00,5696.00,5698.52,5701.69,105.029410,5.992791e+05
97240,97240,2017-10-19 17:15:00,5708.11,5695.00,5701.91,5698.53,70.236143,4.005051e+05
97241,97241,2017-10-19 17:30:00,5702.00,5691.09,5700.44,5701.91,88.787331,5.059870e+05
97242,97242,2017-10-19 17:45:00,5719.71,5700.43,5719.70,5700.44,135.376703,7.734320e+05
97243,97243,2017-10-19 18:00:00,5729.98,5719.69,5719.99,5719.70,121.220791,6.938694e+05
97244,97244,2017-10-19 18:15:00,5719.99,5690.91,5709.95,5719.99,83.856620,4.784865e+05
97245,97245,2017-10-19 18:30:00,5730.00,5705.00,5727.79,5705.00,100.337837,5.739507e+05
97246,97246,2017-10-19 18:45:00,5730.00,5690.00,5711.71,5727.79,116.482618,6.665413e+05
97247,97247,2017-10-19 19:00:00,5723.49,5689.97,5719.74,5711.71,101.137744,5.775619e+05
97248,97248,2017-10-19 19:15:00,5724.99,5710.00,5710.01,5719.74,87.488958,5.003607e+05
97249,97249,2017-10-19 19:30:00,5714.97,5705.25,5712.92,5710.01,36.541138,2.086246e+05
97250,97250,2017-10-19 19:45:00,5712.92,5700.00,5704.01,5712.92,52.212121,2.978099e+05

In [59]:
data.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Mid': 'mid', 'Bid': 'bid', 'Ask': 'ask', 'Last': 'close', 'Volume': 'volume'}, inplace=True)
data

,high,low,mid,close,bid,ask,volume
Date,,,,,,,
2014-04-15,513.9000,452.0000,504.235000,505.000000,503.500000,504.970000,21013.584774
2014-04-16,547.0000,495.0000,537.500000,538.000000,537.000000,538.000000,29633.358705
2014-04-17,538.5000,486.1000,507.020000,508.000000,506.040000,508.000000,20709.783819
2014-04-18,509.0000,474.2500,483.770000,482.750000,482.750000,484.790000,10458.045243
2014-04-19,513.9899,473.8300,505.010650,507.499900,502.531300,507.490000,8963.618369
2014-04-20,517.9950,492.2000,500.745753,501.440000,500.071506,501.420000,4921.588803
2014-04-21,515.6460,485.0000,497.090000,497.000000,497.000000,497.180000,8132.144453
2014-04-22,506.0000,488.8000,491.300003,491.200000,491.209991,491.390015,3105.516105
2014-04-23,496.0000,482.8800,490.819500,490.030000,490.040000,491.599000,4716.703433
2014-04-24,498.8396,480.1600,497.490000,497.980000,497.000000,497.980000,4316.108888
2014-04-25,504.9600,441.3000,464.872500,463.790000,463.790000,465.955000,30376.947882
2014-04-26,469.1900,449.8001,458.300000,457.600000,457.600000,459.000000,8578.837107
2014-04-27,465.6000,440.0000,445.705000,445.000000,445.500000,445.910000,5959.686438
2014-04-28,450.0000,423.1100,445.450000,445.400000,445.400000,445.500000,16467.531309
2014-04-29,454.0000,434.0000,446.275050,445.540000,445.550100,447.000000,8521.438599
2014-04-30,453.6000,432.0000,449.365000,449.370000,449.360000,449.370000,6877.398301
2014-05-01,463.5300,446.9900,459.595000,460.100000,459.100000,460.090000,5339.533294
2014-05-02,461.6699,443.0000,449.655000,449.850000,449.460000,449.850000,3298.963199
2014-05-03,455.0000,430.0000,440.840000,441.300000,440.300000,441.380000,7611.470069
2014-05-04,441.9497,429.0000,436.549950,436.400000,436.200000,436.899900,4157.146647
2014-05-05,444.4000,425.5999,431.493450,430.750000,430.750000,432.236900,5940.594101
2014-05-06,435.3900,419.4000,430.199950,430.899900,429.500000,430.899900,6980.232473
2014-05-07,453.6000,424.2487,445.860000,446.000000,445.720000,446.000000,10468.475615
2014-05-08,450.5900,438.6000,442.745000,442.000000,442.000000,443.490000,4046.403494
2014-05-10,457.0000,448.2000,455.100000,455.000000,455.000000,455.200000,2438.117552
2014-05-11,459.6500,430.0000,436.830000,436.850000,436.810000,436.850000,11882.291187
2014-05-12,442.0000,431.8000,439.405000,439.410000,439.400000,439.410000,3454.204641
2014-05-13,442.0000,434.0100,438.405000,437.820000,437.810000,439.000000,1913.687047
2014-05-14,448.0000,437.8100,447.200000,447.000000,447.000000,447.400000,3086.767474
2014-05-15,451.4000,442.5100,446.685000,446.970000,446.400000,446.970000,1892.639528
...,...,...,...,...,...,...,...
2017-11-02,7350.0000,6625.6000,6989.650000,6987.700000,6989.600000,6989.700000,98593.856763
2017-11-03,7448.0000,6820.0000,7247.250000,7247.200000,7247.200000,7247.300000,63495.495222
2017-11-04,7530.0000,6930.1000,7379.350000,7379.400000,7379.300000,7379.400000,48163.079883
2017-11-05,7598.0000,7272.0000,7329.350000,7321.800000,7327.700000,7331.000000,44704.417996
2017-11-07,7440.0000,6911.0000,6955.700000,6956.500000,6954.900000,6956.500000,63254.491952
2017-11-08,7220.0000,6948.0000,7102.050000,7102.000000,7102.000000,7102.100000,37539.624345
2017-11-09,7899.9000,6977.4000,7447.900000,7447.000000,7446.200000,7449.600000,97308.036492
2017-11-10,7450.0000,7000.0000,7126.450000,7126.400000,7126.400000,7126.500000,50138.924512
2017-11-11,7324.0000,6405.0000,6544.300000,6541.200000,6541.200000,6547.400000,88416.473112
2017-11-12,6789.0000,6163.2000,6301.050000,6302.700000,6299.200000,6302.900000,72841.285950
2017-11-13,6469.6000,5400.2000,5819.350000,5810.700000,5819.300000,5819.400000,172712.471060
2017-11-14,6682.0000,5780.0000,6477.550000,6476.500000,6475.500000,6479.600000,110413.139649
2017-11-15,6689.5000,6301.0000,6589.950000,6590.000000,6589.900000,6590.000000,49485.365842
2017-11-16,7319.0000,6589.9000,7269.100000,7265.840952,7265.900000,7272.300000,71614.834979
2017-11-17,8020.0000,7091.0000,7866.300000,7864.200000,7865.400000,7867.200000,85876.387098
2017-11-18,8040.0000,7505.0000,7674.950000,7675.900000,7674.100000,7675.800000,75935.977364
2017-11-19,7867.8000,7412.0000,7773.250000,7773.300000,7773.200000,7773.300000,40707.793115
2017-11-20,8130.0000,7650.0000,8051.450000,8050.700000,8050.500000,8052.400000,39114.749494
2017-11-21,8315.0000,7925.0000,8249.350000,8248.800000,8248.800000,8249.900000,38281.504925
2017-11-22,8380.0000,7755.6000,8080.850000,8079.300000,8079.100000,8082.600000,71851.273911
2017-11-23,8310.0000,8055.0000,8230.050000,8230.000000,8230.000000,8230.100000,28858.503156
2017-11-24,8268.0000,7970.0000,7981.550000,7985.400000,7977.700000,7985.400000,32136.417133
2017-11-25,8352.1000,7871.0000,8191.300000,8191.600000,8190.900000,8191.700000,42835.274124
2017-11-27,9495.0000,8746.9000,9302.100000,9303.000000,9301.700000,9302.500000,67604.588221
2017-11-28,9771.0000,9231.0000,9725.650000,9725.900000,9725.600000,9725.700000,66628.425821
2017-11-29,9999.0000,9580.8000,9892.350000,9894.900000,9889.800000,9894.900000,47105.820297
2017-11-30,11441.0000,9000.0000,9775.300000,9772.000000,9772.000000,9778.600000,182875.171828
2017-12-01,10542.0000,8801.0000,9907.050000,9907.100000,9907.000000,9907.100000,129048.937966
2017-12-02,10950.0000,9370.1000,10860.500000,10860.000000,10860.000000,10861.000000,84145.007290
2017-12-03,11190.0000,10621.0000,10876.500000,10876.000000,10876.000000,10877.000000,49703.485413

In [156]:
def init_state(data):
#     high = data["high"].values
#     low = data["low"].values
#    mid = data["Weighted_Price"].values
#     last = data["Last"].values
#     bid = data["Bid"].values
#     ask = data["Ask"].values
#     volume = data["Volume"].values
    
 #   priceDiffs = np.diff(mid)
 #   priceDiffs = np.insert(priceDiffs, 0, 0)
    
    # William's %R
    willr = WILLR(data, timeperiod=14)
    # Double Exponential Moving Average
    dema = DEMA(data, timeperiod=30)
    # Chaikin A/D Oscillator
    chaikinOscillator = ADOSC(data, fastperiod=3, slowperiod=10)
    # Chaikin A/D Line
    chaikinLine = AD(data)
    # Normalized Average True Range
    trueRange = NATR(data, timeperiod=14)
    # Linear Regression Slope
    linearRegSlope = LINEARREG_SLOPE(data, timeperiod=14)
    # Standard Deviation
    std = STDDEV(data, timeperiod=5, nbdev=1)
    # Time Series Forecast
    tsf = TSF(data, timeperiod=14)
    
    xdata = np.column_stack((willr, dema, chaikinOscillator, chaikinLine, trueRange, linearRegSlope, std, tsf))
    return xdata

In [157]:
states = init_state(df)

In [158]:
states

array([[             nan,              nan,              nan, ...,
                     nan,              nan,              nan],
       [             nan,              nan,              nan, ...,
                     nan,              nan,              nan],
       [             nan,              nan,              nan, ...,
                     nan,              nan,              nan],
       ...,
       [ -2.10310363e+01,   5.70871700e+03,   3.38508470e+05, ...,
          3.78156044e+00,   6.98212573e+00,   5.73158099e+03],
       [ -1.83222484e+01,   5.71028064e+03,   2.83680741e+05, ...,
          1.86874725e+00,   6.56993940e+00,   5.72267275e+03],
       [ -6.49263053e+01,   5.71054742e+03,   1.99524546e+05, ...,
          1.21419780e+00,   5.06201301e+00,   5.71856220e+03]])

In [159]:
import csv

with open("output.csv", "wb") as f:
    writer = csv.writer(f)
    writer.writerows(states)