In [114]:
import pandas as pd
import numpy as np
import quandl
from talib.abstract import *
import datetime
def dateparse (time_in_secs):    
    return datetime.datetime.fromtimestamp(float(time_in_secs))

In [115]:
df = pd.read_csv("coinbaseUSD_1-min_data_2014-12-01_to_2017-10-20.csv", parse_dates=True,date_parser=dateparse, index_col='Timestamp')

In [103]:
data = quandl.get("BITFINEX/BTCUSD")

In [116]:
df

,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
Timestamp,,,,,,,
2014-12-01 00:33:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:34:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:35:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:36:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:37:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:38:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:39:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:40:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:41:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:42:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:43:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:44:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:45:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:46:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:47:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:48:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:49:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:50:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:51:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:52:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:53:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:54:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:55:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:56:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:57:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:58:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:59:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 01:00:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 01:01:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 01:02:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
...,...,...,...,...,...,...,...
2017-10-19 19:31:00,5710.01,5710.01,5710.01,5710.01,3.513269,20060.799238,5710.010000
2017-10-19 19:32:00,5710.01,5710.01,5710.01,5710.01,4.164801,23781.053474,5710.010000
2017-10-19 19:33:00,5710.01,5710.01,5710.01,5710.01,4.516794,25790.938565,5710.010000
2017-10-19 19:34:00,5710.01,5710.01,5710.00,5710.01,2.019386,11530.710812,5710.009257
2017-10-19 19:35:00,5710.01,5710.02,5710.01,5710.02,0.170122,971.398422,5710.018983
2017-10-19 19:36:00,5710.02,5714.71,5710.02,5713.26,4.001121,22851.586000,5711.296038
2017-10-19 19:37:00,5713.19,5713.19,5711.35,5711.35,0.393821,2249.249057,5711.350008
2017-10-19 19:38:00,5711.35,5711.35,5705.26,5705.26,4.823917,27543.271097,5709.731232
2017-10-19 19:39:00,5705.26,5705.26,5705.26,5705.26,3.684556,21021.348881,5705.260000
2017-10-19 19:40:00,5705.26,5705.26,5705.25,5705.26,1.638952,9350.645964,5705.257835
2017-10-19 19:41:00,5705.26,5705.26,5705.25,5705.25,1.690246,9643.277577,5705.251748
2017-10-19 19:42:00,5705.26,5711.26,5705.26,5711.26,1.474186,8414.649523,5707.997020
2017-10-19 19:43:00,5711.00,5711.00,5710.04,5711.00,1.379121,7875.482736,5710.509266
2017-10-19 19:44:00,5711.00,5714.97,5711.00,5712.92,1.861873,10636.937866,5713.031759
2017-10-19 19:45:00,5712.92,5712.92,5707.68,5707.69,3.639256,20777.448395,5709.257730
2017-10-19 19:46:00,5707.69,5707.69,5707.68,5707.69,2.935604,16755.507280,5707.685728
2017-10-19 19:47:00,5707.69,5707.69,5705.28,5707.47,1.436433,8196.459619,5706.121455
2017-10-19 19:48:00,5706.83,5706.83,5705.24,5705.24,6.485168,37000.196467,5705.356919
2017-10-19 19:49:00,5705.25,5705.25,5705.24,5705.25,6.538862,37305.798548,5705.243621
2017-10-19 19:50:00,5705.25,5705.25,5705.24,5705.25,2.551726,14558.235178,5705.249895
2017-10-19 19:51:00,5705.25,5705.25,5705.24,5705.25,2.645729,15094.527857,5705.243162
2017-10-19 19:52:00,5705.01,5705.01,5705.01,5705.01,2.239995,12779.191992,5705.010000
2017-10-19 19:53:00,5705.01,5705.01,5701.01,5701.01,1.906660,10877.267534,5704.881021
2017-10-19 19:54:00,5703.22,5703.22,5700.00,5700.00,4.793786,27325.020313,5700.091678
2017-10-19 19:55:00,5700.01,5700.01,5700.00,5700.00,1.492222,8505.677349,5700.009268
2017-10-19 19:56:00,5700.01,5700.01,5700.00,5700.01,4.107598,23413.350886,5700.009878
2017-10-19 19:57:00,5700.01,5700.54,5700.01,5700.54,3.377075,19250.702466,5700.407366
2017-10-19 19:58:00,5700.54,5704.01,5700.53,5704.01,5.572255,31770.431877,5701.539951
2017-10-19 19:59:00,5703.96,5704.01,5702.87,5704.01,2.489754,14200.042922,5703.392752
2017-10-19 20:00:00,5704.00,5704.01,5704.00,5704.01,1.700455,9699.411610,5704.009412

In [120]:
df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close', 'Volume_(Currency)': 'volume'}, inplace=True)
df

,open,high,low,close,Volume_(BTC),volume,Weighted_Price
Timestamp,,,,,,,
2014-12-01 00:33:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:34:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:35:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:36:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:37:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:38:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:39:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:40:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:41:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:42:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:43:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:44:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:45:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:46:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:47:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:48:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:49:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:50:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:51:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:52:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:53:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:54:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:55:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:56:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:57:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:58:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 00:59:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 01:00:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 01:01:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 01:02:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
...,...,...,...,...,...,...,...
2017-10-19 19:31:00,5710.01,5710.01,5710.01,5710.01,3.513269,20060.799238,5710.010000
2017-10-19 19:32:00,5710.01,5710.01,5710.01,5710.01,4.164801,23781.053474,5710.010000
2017-10-19 19:33:00,5710.01,5710.01,5710.01,5710.01,4.516794,25790.938565,5710.010000
2017-10-19 19:34:00,5710.01,5710.01,5710.00,5710.01,2.019386,11530.710812,5710.009257
2017-10-19 19:35:00,5710.01,5710.02,5710.01,5710.02,0.170122,971.398422,5710.018983
2017-10-19 19:36:00,5710.02,5714.71,5710.02,5713.26,4.001121,22851.586000,5711.296038
2017-10-19 19:37:00,5713.19,5713.19,5711.35,5711.35,0.393821,2249.249057,5711.350008
2017-10-19 19:38:00,5711.35,5711.35,5705.26,5705.26,4.823917,27543.271097,5709.731232
2017-10-19 19:39:00,5705.26,5705.26,5705.26,5705.26,3.684556,21021.348881,5705.260000
2017-10-19 19:40:00,5705.26,5705.26,5705.25,5705.26,1.638952,9350.645964,5705.257835
2017-10-19 19:41:00,5705.26,5705.26,5705.25,5705.25,1.690246,9643.277577,5705.251748
2017-10-19 19:42:00,5705.26,5711.26,5705.26,5711.26,1.474186,8414.649523,5707.997020
2017-10-19 19:43:00,5711.00,5711.00,5710.04,5711.00,1.379121,7875.482736,5710.509266
2017-10-19 19:44:00,5711.00,5714.97,5711.00,5712.92,1.861873,10636.937866,5713.031759
2017-10-19 19:45:00,5712.92,5712.92,5707.68,5707.69,3.639256,20777.448395,5709.257730
2017-10-19 19:46:00,5707.69,5707.69,5707.68,5707.69,2.935604,16755.507280,5707.685728
2017-10-19 19:47:00,5707.69,5707.69,5705.28,5707.47,1.436433,8196.459619,5706.121455
2017-10-19 19:48:00,5706.83,5706.83,5705.24,5705.24,6.485168,37000.196467,5705.356919
2017-10-19 19:49:00,5705.25,5705.25,5705.24,5705.25,6.538862,37305.798548,5705.243621
2017-10-19 19:50:00,5705.25,5705.25,5705.24,5705.25,2.551726,14558.235178,5705.249895
2017-10-19 19:51:00,5705.25,5705.25,5705.24,5705.25,2.645729,15094.527857,5705.243162
2017-10-19 19:52:00,5705.01,5705.01,5705.01,5705.01,2.239995,12779.191992,5705.010000
2017-10-19 19:53:00,5705.01,5705.01,5701.01,5701.01,1.906660,10877.267534,5704.881021
2017-10-19 19:54:00,5703.22,5703.22,5700.00,5700.00,4.793786,27325.020313,5700.091678
2017-10-19 19:55:00,5700.01,5700.01,5700.00,5700.00,1.492222,8505.677349,5700.009268
2017-10-19 19:56:00,5700.01,5700.01,5700.00,5700.01,4.107598,23413.350886,5700.009878
2017-10-19 19:57:00,5700.01,5700.54,5700.01,5700.54,3.377075,19250.702466,5700.407366
2017-10-19 19:58:00,5700.54,5704.01,5700.53,5704.01,5.572255,31770.431877,5701.539951
2017-10-19 19:59:00,5703.96,5704.01,5702.87,5704.01,2.489754,14200.042922,5703.392752
2017-10-19 20:00:00,5704.00,5704.01,5704.00,5704.01,1.700455,9699.411610,5704.009412

In [59]:
data.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Mid': 'mid', 'Bid': 'bid', 'Ask': 'ask', 'Last': 'close', 'Volume': 'volume'}, inplace=True)
data

,high,low,mid,close,bid,ask,volume
Date,,,,,,,
2014-04-15,513.9000,452.0000,504.235000,505.000000,503.500000,504.970000,21013.584774
2014-04-16,547.0000,495.0000,537.500000,538.000000,537.000000,538.000000,29633.358705
2014-04-17,538.5000,486.1000,507.020000,508.000000,506.040000,508.000000,20709.783819
2014-04-18,509.0000,474.2500,483.770000,482.750000,482.750000,484.790000,10458.045243
2014-04-19,513.9899,473.8300,505.010650,507.499900,502.531300,507.490000,8963.618369
2014-04-20,517.9950,492.2000,500.745753,501.440000,500.071506,501.420000,4921.588803
2014-04-21,515.6460,485.0000,497.090000,497.000000,497.000000,497.180000,8132.144453
2014-04-22,506.0000,488.8000,491.300003,491.200000,491.209991,491.390015,3105.516105
2014-04-23,496.0000,482.8800,490.819500,490.030000,490.040000,491.599000,4716.703433
2014-04-24,498.8396,480.1600,497.490000,497.980000,497.000000,497.980000,4316.108888
2014-04-25,504.9600,441.3000,464.872500,463.790000,463.790000,465.955000,30376.947882
2014-04-26,469.1900,449.8001,458.300000,457.600000,457.600000,459.000000,8578.837107
2014-04-27,465.6000,440.0000,445.705000,445.000000,445.500000,445.910000,5959.686438
2014-04-28,450.0000,423.1100,445.450000,445.400000,445.400000,445.500000,16467.531309
2014-04-29,454.0000,434.0000,446.275050,445.540000,445.550100,447.000000,8521.438599
2014-04-30,453.6000,432.0000,449.365000,449.370000,449.360000,449.370000,6877.398301
2014-05-01,463.5300,446.9900,459.595000,460.100000,459.100000,460.090000,5339.533294
2014-05-02,461.6699,443.0000,449.655000,449.850000,449.460000,449.850000,3298.963199
2014-05-03,455.0000,430.0000,440.840000,441.300000,440.300000,441.380000,7611.470069
2014-05-04,441.9497,429.0000,436.549950,436.400000,436.200000,436.899900,4157.146647
2014-05-05,444.4000,425.5999,431.493450,430.750000,430.750000,432.236900,5940.594101
2014-05-06,435.3900,419.4000,430.199950,430.899900,429.500000,430.899900,6980.232473
2014-05-07,453.6000,424.2487,445.860000,446.000000,445.720000,446.000000,10468.475615
2014-05-08,450.5900,438.6000,442.745000,442.000000,442.000000,443.490000,4046.403494
2014-05-10,457.0000,448.2000,455.100000,455.000000,455.000000,455.200000,2438.117552
2014-05-11,459.6500,430.0000,436.830000,436.850000,436.810000,436.850000,11882.291187
2014-05-12,442.0000,431.8000,439.405000,439.410000,439.400000,439.410000,3454.204641
2014-05-13,442.0000,434.0100,438.405000,437.820000,437.810000,439.000000,1913.687047
2014-05-14,448.0000,437.8100,447.200000,447.000000,447.000000,447.400000,3086.767474
2014-05-15,451.4000,442.5100,446.685000,446.970000,446.400000,446.970000,1892.639528
...,...,...,...,...,...,...,...
2017-11-02,7350.0000,6625.6000,6989.650000,6987.700000,6989.600000,6989.700000,98593.856763
2017-11-03,7448.0000,6820.0000,7247.250000,7247.200000,7247.200000,7247.300000,63495.495222
2017-11-04,7530.0000,6930.1000,7379.350000,7379.400000,7379.300000,7379.400000,48163.079883
2017-11-05,7598.0000,7272.0000,7329.350000,7321.800000,7327.700000,7331.000000,44704.417996
2017-11-07,7440.0000,6911.0000,6955.700000,6956.500000,6954.900000,6956.500000,63254.491952
2017-11-08,7220.0000,6948.0000,7102.050000,7102.000000,7102.000000,7102.100000,37539.624345
2017-11-09,7899.9000,6977.4000,7447.900000,7447.000000,7446.200000,7449.600000,97308.036492
2017-11-10,7450.0000,7000.0000,7126.450000,7126.400000,7126.400000,7126.500000,50138.924512
2017-11-11,7324.0000,6405.0000,6544.300000,6541.200000,6541.200000,6547.400000,88416.473112
2017-11-12,6789.0000,6163.2000,6301.050000,6302.700000,6299.200000,6302.900000,72841.285950
2017-11-13,6469.6000,5400.2000,5819.350000,5810.700000,5819.300000,5819.400000,172712.471060
2017-11-14,6682.0000,5780.0000,6477.550000,6476.500000,6475.500000,6479.600000,110413.139649
2017-11-15,6689.5000,6301.0000,6589.950000,6590.000000,6589.900000,6590.000000,49485.365842
2017-11-16,7319.0000,6589.9000,7269.100000,7265.840952,7265.900000,7272.300000,71614.834979
2017-11-17,8020.0000,7091.0000,7866.300000,7864.200000,7865.400000,7867.200000,85876.387098
2017-11-18,8040.0000,7505.0000,7674.950000,7675.900000,7674.100000,7675.800000,75935.977364
2017-11-19,7867.8000,7412.0000,7773.250000,7773.300000,7773.200000,7773.300000,40707.793115
2017-11-20,8130.0000,7650.0000,8051.450000,8050.700000,8050.500000,8052.400000,39114.749494
2017-11-21,8315.0000,7925.0000,8249.350000,8248.800000,8248.800000,8249.900000,38281.504925
2017-11-22,8380.0000,7755.6000,8080.850000,8079.300000,8079.100000,8082.600000,71851.273911
2017-11-23,8310.0000,8055.0000,8230.050000,8230.000000,8230.000000,8230.100000,28858.503156
2017-11-24,8268.0000,7970.0000,7981.550000,7985.400000,7977.700000,7985.400000,32136.417133
2017-11-25,8352.1000,7871.0000,8191.300000,8191.600000,8190.900000,8191.700000,42835.274124
2017-11-27,9495.0000,8746.9000,9302.100000,9303.000000,9301.700000,9302.500000,67604.588221
2017-11-28,9771.0000,9231.0000,9725.650000,9725.900000,9725.600000,9725.700000,66628.425821
2017-11-29,9999.0000,9580.8000,9892.350000,9894.900000,9889.800000,9894.900000,47105.820297
2017-11-30,11441.0000,9000.0000,9775.300000,9772.000000,9772.000000,9778.600000,182875.171828
2017-12-01,10542.0000,8801.0000,9907.050000,9907.100000,9907.000000,9907.100000,129048.937966
2017-12-02,10950.0000,9370.1000,10860.500000,10860.000000,10860.000000,10861.000000,84145.007290
2017-12-03,11190.0000,10621.0000,10876.500000,10876.000000,10876.000000,10877.000000,49703.485413

In [127]:
def init_state(marketData):
#     high = data["high"].values
#     low = data["low"].values
#    mid = data["Weighted_Price"].values
#     last = data["Last"].values
#     bid = data["Bid"].values
#     ask = data["Ask"].values
#     volume = data["Volume"].values
    
 #   priceDiffs = np.diff(mid)
 #   priceDiffs = np.insert(priceDiffs, 0, 0)
    
    # William's %R
    willr = WILLR(data, timeperiod=14)
    # Double Exponential Moving Average
    dema = DEMA(data, timeperiod=30)
    # Chaikin A/D Oscillator
    chaikinOscillator = ADOSC(data, fastperiod=3, slowperiod=10)
    # Chaikin A/D Line
    chaikinLine = AD(data)
    # Normalized Average True Range
    trueRange = NATR(data, timeperiod=14)
    # Linear Regression Slop
    linearRegSlope = LINEARREG_SLOPE(data, timeperiod=14)
    # Standard Deviation
    std = STDDEV(data, timeperiod=5, nbdev=1)
    # Time Series Forecast
    tsf = TSF(data, timeperiod=14)
    
    xdata = np.column_stack((willr, dema, chaikinOscillator, chaikinLine, trueRange, linearRegSlope, std, tsf))
    return xdata

In [128]:
states = init_state(df)

NameError: global name 'mid' is not defined

In [93]:
real = LINEARREG_ANGLE(data, timeperiod=14)

In [94]:
real

Date
2014-04-15          NaN
2014-04-16          NaN
2014-04-17          NaN
2014-04-18          NaN
2014-04-19          NaN
2014-04-20          NaN
2014-04-21          NaN
2014-04-22          NaN
2014-04-23          NaN
2014-04-24          NaN
2014-04-25          NaN
2014-04-26          NaN
2014-04-27          NaN
2014-04-28   -79.569750
2014-04-29   -80.659010
2014-04-30   -79.250898
2014-05-01   -78.108182
2014-05-02   -78.999939
2014-05-03   -78.288846
2014-05-04   -77.611030
2014-05-05   -76.916049
2014-05-06   -75.788692
2014-05-07   -71.195649
2014-05-08   -57.726662
2014-05-10   -36.495802
2014-05-11   -30.123202
2014-05-12   -33.886377
2014-05-13   -37.621568
2014-05-14   -29.664118
2014-05-15   -14.005389
                ...
2017-11-02    89.085958
2017-11-03    89.398424
2017-11-04    89.553899
2017-11-05    89.614964
2017-11-07    89.622668
2017-11-08    89.594292
2017-11-09    89.588143
2017-11-10    89.548770
2017-11-11    89.357541
2017-11-12    88.572811
2017-11-13   -84.698440
2017-11-14   -88.698372
2017-11-15   -89.132099
2017-11-16   -89.055165
2017-11-17   -88.090701
2017-11-18    -2.156253
2017-11-19    88.371750
2017-11-20    89.232944
2017-11-21    89.452342
2017-11-22    89.555219
2017-11-23    89.651485
2017-11-24    89.679880
2017-11-25    89.675172
2017-11-27    89.699126
2017-11-28    89.693850
2017-11-29    89.703799
2017-11-30    89.690170
2017-12-01    89.696158
2017-12-02    89.748213
2017-12-03    89.768618
Length: 1298, dtype: float64